name: al_quran_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  http: ^0.13.3
  equatable: ^2.0.2
  flutter_bloc: ^8.1.1
  get_it: ^7.1.3
  google_fonts: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.4
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8

flutter:
  uses-material-design: true

  # assets:
    # - assets/
  