name: al_quran_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  get_it: ^7.1.3
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  http: ^0.13.3
  lottie: ^2.1.0
  sqflite: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.0.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/lottie/
    - assets/data/
