// Mocks generated by Mockito 5.3.2 from annotations
// in al_quran_app/test/presentation/bloc/quran_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:al_quran_app/common/failure.dart' as _i6;
import 'package:al_quran_app/domain/entities/surah_entities/detail_surah_entities/detail_surah_entities.dart'
    as _i9;
import 'package:al_quran_app/domain/entities/surah_entities/list_surah_entities/surah_entities.dart'
    as _i7;
import 'package:al_quran_app/domain/repositories/quran_repository.dart' as _i2;
import 'package:al_quran_app/domain/usecases/get_detail_surah.dart' as _i8;
import 'package:al_quran_app/domain/usecases/get_surah_list.dart' as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSurahRepository_0 extends _i1.SmartFake
    implements _i2.SurahRepository {
  _FakeSurahRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetSurahList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSurahList extends _i1.Mock implements _i4.GetSurahList {
  MockGetSurahList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SurahRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSurahRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SurahRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.SurahEntities>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.SurahEntities>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.SurahEntities>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.SurahEntities>>>);
}

/// A class which mocks [GetDetailSurah].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDetailSurah extends _i1.Mock implements _i8.GetDetailSurah {
  MockGetDetailSurah() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SurahRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSurahRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SurahRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i9.DetailSurahEntities>> execute(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i9.DetailSurahEntities>>.value(
                _FakeEither_1<_i6.Failure, _i9.DetailSurahEntities>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i9.DetailSurahEntities>>);
}
